name: Issue
description: I have a bug and I must fix
title: "[Bug]: "
labels: ["bug"]

body:
  - type: dropdown
    id: modding_method
    attributes:
      label: How are you modding?
      options:
        - Source
        - Softmod
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: "Enter the version number (format: #.#.#)"
      placeholder: "e.g., 1.2.3"
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: Briefly describe the issue
      placeholder: "What happened? What did you expect?"
    validations:
      required: true

  - type: textarea
    id: console_errors
    attributes:
      label: Any console errors?
      description: "Paste any logs or error messages here."
      placeholder: "Include stack traces or relevant output..."
